### ISSUE TITLE
Harmony builds are published to PackageCloud

### ISSUE THREAD

**Issue by tfitch** [chef/omnibus-harmony#11]
Since this app doesn't do anything, why are we publishing it's builds to PackageCloud?

I went to the /chef/current section of PackageCloud yesterday, saw the Harmony builds.  Went on a hunt to figure out what they are and found out they do nothing.  Therefore I think they shouldn't be published  as they don't appear to be of any value to a user.

Just a thought.

**Comment by sethvargo** [comment]
@tfitch it's for testing purposes. It's a full integration test from build to deploy.

**Comment by tfitch** [comment]
Right, but I feel they should be published somewhere else so users don't stumble upon a Harmony package and wonder why product they're missing out on.  It's not a functionality thing, this is a usability thing.

**Comment by sethvargo** [comment]
Sure - if you want to publish them to a different packagecloud account it should be fine /cc @schisamo
